[book]
title = "Game Programming with Usagi Engine"
authors = ["Brett Chalupa"]
language = "en"
description = "A beginner-friendly guide to programming 2D games in Lua with Usagi Engine."

[output.html]
git-repository-url = "https://github.com/brettchalupa/usagi_book"
